spring:
  version: 1.0.0
  title: AutoTransactionLogger
  application:
    name: auto-transaction-logger
  profiles:
    active: local
  jpa:
    show-sql: true

datasource:
  url: jdbc:h2:file:./src/main/resources/data
  driverClassName: org.h2.Driver
  username: nmy
  password: nmy

h2:
  console:
    enabled: true
    path: /h2-console

logging:
  level:
    root: DEBUG

auto-tren-loger:
  isConsoleLog: true
  isDatabaseLog: true
  logLevel: DEBUG